input{
    file{
        path => "/home/realelvo/Desktop/Projects/logstash_project/nginx_access.log"
        start_position => "beginning"
        sincedb_path => "/dev/null"
    }
}


filter{
    grok{
        match =>{
            "message" => "%{IPV4:ip} - - \[%{HTTPDATE:timestamp}\] \"%{WORD:method} %{URIPATH:request} HTTP/%{NUMBER:http_version}\" %{NUMBER:status} %{NUMBER:bytes}"
        }
    }

    date{
        match => ["timestamp":"dd/MMM/yyy:HH:mm:ss Z"]
    }

    geoip{
        source => "ip"
    }
}


output{
    elasticsearch{
        hosts => ["https://localhost:9200"]
        index => "nginx-logs-%{+YY-mm-dd}"
    }
    stdout{
        codec => rubydebug
    }
}